Disable faulty test (#31)
The picker test is causing a fatal error given the following crash report details:

HarnessEventHandler.swift:182: Fatal error: Issue 'Expectation failed: (color.wrappedValue → nil) == (expectedColor → .red)' was recorded at CartographyMapPinColorPickerTests.swift:26:13 without an associated test. This may be due to calling #expect() or Issue.record() from a detached Task or another unknown context.